### ISSUE TITLE
Deprecated selector in `monokai-dark/index.less`

### ISSUE THREAD

**Issue by christianstanfield** [james2doyle/atom-monokai-dark#12]
In `monokai-dark/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host ::-webkit-scrollbar,
atom-text-editor ::-webkit-scrollbar` => `atom-text-editor ::-webkit-scrollbar,
atom-text-editor ::-webkit-scrollbar`

* `:host ::-webkit-scrollbar-track,
atom-text-editor ::-webkit-scrollbar-track` => `atom-text-editor ::-webkit-scrollbar-track,
atom-text-editor ::-webkit-scrollbar-track`

* `:host ::-webkit-scrollbar-thumb,
atom-text-editor ::-webkit-scrollbar-thumb` => `atom-text-editor ::-webkit-scrollbar-thumb,
atom-text-editor ::-webkit-scrollbar-thumb`

* `:host .wrap-guide,
atom-text-editor .wrap-guide` => `atom-text-editor .wrap-guide,
atom-text-editor .wrap-guide`

* `:host .indent-guide,
atom-text-editor .indent-guide` => `atom-text-editor .indent-guide,
atom-text-editor .indent-guide`

* `:host,
atom-text-editor,
:host .gutter,
atom-text-editor .gutter` => `atom-text-editor,
atom-text-editor,atom-text-editor .gutter,
atom-text-editor .gutter`

* `:host.is-focused .cursor,
atom-text-editor.is-focused .cursor` => `atom-text-editor.is-focused .cursor,
atom-text-editor.is-focused .cursor`

* `:host.is-focused .selection .region,
atom-text-editor.is-focused .selection .region` => `atom-text-editor.is-focused .selection .region,
atom-text-editor.is-focused .selection .region`

* `:host.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line-number.cursor-line-no-selection,
:host.is-focused .line.cursor-line,
atom-text-editor.is-focused .line.cursor-line` => `atom-text-editor.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line-number.cursor-line-no-selection,atom-text-editor.is-focused .line.cursor-line,
atom-text-editor.is-focused .line.cursor-line`

* `:host .comment,
atom-text-editor .comment` => `atom-text-editor .syntax--comment,
atom-text-editor .syntax--comment`

* `:host .string,
atom-text-editor .string` => `atom-text-editor .syntax--string,
atom-text-editor .syntax--string`

* `:host .constant.numeric,
atom-text-editor .constant.numeric` => `atom-text-editor .syntax--constant.syntax--numeric,
atom-text-editor .syntax--constant.syntax--numeric`

* `:host .constant.language,
atom-text-editor .constant.language` => `atom-text-editor .syntax--constant.syntax--language,
atom-text-editor .syntax--constant.syntax--language`

* `:host .constant.character,
atom-text-editor .constant.character,
:host .constant.other,
atom-text-editor .constant.other` => `atom-text-editor .syntax--constant.syntax--character,
atom-text-editor .syntax--constant.syntax--character,atom-text-editor .syntax--constant.syntax--other,
atom-text-editor .syntax--constant.syntax--other`

* `:host .keyword,
atom-text-editor .keyword` => `atom-text-editor .syntax--keyword,
atom-text-editor .syntax--keyword`

* `:host .storage,
atom-text-editor .storage` => `atom-text-editor .syntax--storage,
atom-text-editor .syntax--storage`

* `:host .storage.type,
atom-text-editor .storage.type` => `atom-text-editor .syntax--storage.syntax--type,
atom-text-editor .syntax--storage.syntax--type`

* `:host .entity.name.class,
atom-text-editor .entity.name.class` => `atom-text-editor .syntax--entity.syntax--name.syntax--class,
atom-text-editor .syntax--entity.syntax--name.syntax--class`

* `:host .entity.other.inherited-class,
atom-text-editor .entity.other.inherited-class` => `atom-text-editor .syntax--entity.syntax--other.syntax--inherited-class,
atom-text-editor .syntax--entity.syntax--other.syntax--inherited-class`

* `:host .entity.name.function,
atom-text-editor .entity.name.function` => `atom-text-editor .syntax--entity.syntax--name.syntax--function,
atom-text-editor .syntax--entity.syntax--name.syntax--function`

* `:host .variable.parameter,
atom-text-editor .variable.parameter` => `atom-text-editor .syntax--variable.syntax--parameter,
atom-text-editor .syntax--variable.syntax--parameter`

* `:host .entity.name.tag,
atom-text-editor .entity.name.tag` => `atom-text-editor .syntax--entity.syntax--name.syntax--tag,
atom-text-editor .syntax--entity.syntax--name.syntax--tag`

* `:host .entity.other.attribute-name,
atom-text-editor .entity.other.attribute-name` => `atom-text-editor .syntax--entity.syntax--other.syntax--attribute-name,
atom-text-editor .syntax--entity.syntax--other.syntax--attribute-name`

* `:host .support.function,
atom-text-editor .support.function` => `atom-text-editor .syntax--support.syntax--function,
atom-text-editor .syntax--support.syntax--function`

* `:host .support.constant,
atom-text-editor .support.constant` => `atom-text-editor .syntax--support.syntax--constant,
atom-text-editor .syntax--support.syntax--constant`

* `:host .support.type,
atom-text-editor .support.type,
:host .support.class,
atom-text-editor .support.class` => `atom-text-editor .syntax--support.syntax--type,
atom-text-editor .syntax--support.syntax--type,atom-text-editor .syntax--support.syntax--class,
atom-text-editor .syntax--support.syntax--class`

* `:host .invalid,
atom-text-editor .invalid` => `atom-text-editor .syntax--invalid,
atom-text-editor .syntax--invalid`

* `:host .invalid.deprecated,
atom-text-editor .invalid.deprecated` => `atom-text-editor .syntax--invalid.syntax--deprecated,
atom-text-editor .syntax--invalid.syntax--deprecated`

* `atom-text-editor::shadow .is-focused .selection .region` => `atom-text-editor.editor .is-focused .selection .region`

* `atom-text-editor::shadow .is-focused .line-number.cursor-line-no-selection,
atom-text-editor::shadow .is-focused .line.cursor-line` => `atom-text-editor.editor .is-focused .line-number.cursor-line-no-selection,
atom-text-editor.editor .is-focused .line.cursor-line`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by james2doyle** [comment]
Closed with #14
