### ISSUE TITLE
Warning: Deprecated selectors

### ISSUE THREAD

**Issue by cat-j** [james2doyle/atom-monokai-dark#16]
Atom v1.24.0 throws the following warning message regarding this theme:

> Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
> - `:host ::-webkit-scrollbar, atom-text-editor ::-webkit-scrollbar => atom-text-editor ::-webkit-scrollbar, atom-text-editor ::-webkit-scrollbar`
>  - `<some more selectors following the same pattern>`
>  - `:host .wrap-guide, atom-text-editor .wrap-guide => atom-text-editor .wrap-guide, atom-text-editor .wrap-guide`
> - `:host .indent-guide, atom-text-editor .indent-guide => atom-text-editor .indent-guide, atom-text-editor .indent-guide`
> - `:host, atom-text-editor, :host .gutter, atom-text-editor .gutter => atom-text-editor, atom-text-editor,atom-text-editor .gutter, atom-text-editor .gutter`
> - `<a lot more selectors`>
>
> Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

So right now, it's working properly, but some selectors are deprecated so this package might break soon.

I can fix it if you'd like -- just felt like asking beforehand because this is my first contribution. Cheers!

**Comment by james2doyle** [comment]
Yes, please give it a shot!

**Comment by cat-j** [comment]
For some weird reason, the code in this repo is updated (no `host::` before selectors), but the package that gets installed from Atom is not. `index.less:19` from the repo is
```
atom-text-editor {
```
whereas on `~/.atom/packages` it's
```
:host, atom-text-editor {
```
I tried to open a pull request on atom.io but it doesn't seem to be possible. Can contributors update the package or does the creator have to do it?

**Comment by james2doyle** [comment]
I'm not sure actually

**Comment by adambharris** [comment]
@james2doyle All that's left is for you to publish the latest version. Info on `apm publish` [here](https://flight-manual.atom.io/hacking-atom/sections/publishing/). It should also resolve issue https://github.com/james2doyle/atom-monokai-dark/issues/15.
